# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million,
# find the sum of the even-valued terms.

a = 1
b = 2
c = b
sum_even = c

while c < 4000001
    b+=a
    a = c
    c = b
    if c % 2 == 0
        sum_even += c
    end
end

puts sum_even

